name: pipemap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_map: any # or the latest version on Pub
  flutter:
    sdk: flutter
  toggle_switch: "^0.1.8"
  english_words: ^3.1.5
  geolocator: "7.0.1"
  arcore_flutter_plugin: ^0.010
  flutter_map_tappable_polyline: any
  flutter_compass: '^0.4.3'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies: 
  flutter_launcher_icons: ^0.8.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/pipelogo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/pipelogo.png
    - lib/assets/images/small_pipe_logo.png
    - lib/assets/data/
  
